exclude_paths:
- lib/main.rb
- lib/subjects_main.rb
- lib/email_main.rb
- lib/login_main.rb
- lib/menu_main.rb
- lib/notifications_main.rb
- lib/signin_ma
- lib
- config
- test/test_helper.rb
- db/migrate
- test/application_system_test_case.rb