require: rubocop-rspec

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']
AllCops:
  Exclude:
    - 'lib/model/*'
    - 'lib/helpers/*'
    - 'lib/controllers/*'
    - 'lib/*'
    - 'specOld/*'
    - 'specOld/customMatchers/*'
    - 'app/*'
    - 'test/*'
    - 'db/*'
    - 'config/*'
    - 'config/environments/*'
    - 'Gemfile'
    - 'bin/*'
    - 'config/initializers/*'
    - 'Rakefile'