require: rubocop-rspec

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']
AllCops:
  Exclude:
    - 'lib/models/subjects_main.rb'
    - 'app/*'
    - 'test/*'
    - 'db/*'
    - 'config/*'
    - 'config/environments/*'
    - 'Gemfile'
    - 'bin/*'
    - 'config/initializers/*'
    - 'Rakefile'